### ISSUE TITLE
xlink:href property id not working properly

### ISSUE THREAD

**Issue by Xheldon** [laleksiunas/inline-svg-unique-id#1]
I use the babel plugin to solve the svg id problem, but there have some problem when i use it.

I have a svg, the structure like this below:

```
svg
  circle id="a"
  g
     use xlink:href="#a"
```
the svg:
ref: 
![image](https://user-images.githubusercontent.com/9780154/147659235-fecf2b88-8f01-4abf-ae14-65af1f54b45b.png)

use in:
![image](https://user-images.githubusercontent.com/9780154/147657941-de25c212-a8d2-4810-8f5a-300ba338e257.png)

and the dist .tsx:

ref:
![image](https://user-images.githubusercontent.com/9780154/147659307-ce9d83a0-ba7a-4c29-98aa-2f26bdef7d22.png)

use in:
![image](https://user-images.githubusercontent.com/9780154/147658004-8f1fc37a-2f0f-4bf2-bba9-2fcfc181c8d6.png)

After build, the id not change to someting like `const _id = useUniqueInlineId();` `use xlink:href={_id}` and still is `use xlink:href="#a"` --- just a string,not a var.

I think maybe it's a bug? How should I solve to? thx!

**Comment by Xheldon** [comment]
I notice that you just deal with the `url()` iri, so, maybe I should submit a PR?

https://github.com/laleksiunas/inline-svg-unique-id/blob/af5d2f9e382cc0ab89f03f271f0fedc9d571875b/packages/babel-plugin-react-inline-svg-unique-id/src/plugin.js#L12

**Comment by laleksiunas** [comment]
Thanks, this plugin doesn't handle such _xlink:href_ values indeed. It would be great if you could submit a PR.

**Comment by laleksiunas** [comment]
@Xheldon I published a new plugin version 1.3.0 which contains the fix for such `xlink:href` values. Please verify on your end.

**Comment by malie666** [comment]
@laleksiunas Hello, the problem about xlink:href is still exists. It seems like `isXlinkHrefAttribute` function has bug，`isXlinkHrefAttribute` return always false.

https://github.com/laleksiunas/inline-svg-unique-id/blob/17cff0f6b1d7e9daa5e5c372407a77a3f8918911/packages/babel-plugin-react-inline-svg-unique-id/src/plugin.js#L44

**Comment by laleksiunas** [comment]
Hi @Gulululala, can you provide a SVG sample? I currently run a test on such icon and the xlink:href property is replaced correctly:
```
const Icon = () => (
  <svg height="150" width="400">
    <defs>
      <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
        <stop offset="0%" style="stop-color:rgb(255,255,0);stop-opacity:1" />
        <stop offset="100%" style="stop-color:rgb(255,0,0);stop-opacity:1" />
      </linearGradient>
    </defs>
    <ellipse cx="200" cy="70" rx="85" ry="55" xlink:href="#grad1" />
  </svg>
);
```
Maybe I'm missing some case? Is the element referenced by xlink:href defined in the `<defs>` block?

**Comment by Gulululala** [comment]
@laleksiunas Please help check this case, thx !
```
<svg width="12" height="12" viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <linearGradient x1="19.617%" y1="8.88%" x2="83.953%" y2="93.968%" id="a" gradientUnits="userSpaceOnUse">
            <stop stop-color="#FFC174" offset="0%"/>
            <stop stop-color="#FFA200" offset="100%"/>
        </linearGradient>
        <path
            d="m6 9-2.15 1.13a.768.768 0 0 1-1.114-.81l.41-2.393-1.738-1.695a.768.768 0 0 1 .426-1.31l2.403-.35L5.31 1.396a.768.768 0 0 1 1.378 0l1.074 2.178 2.403.35a.768.768 0 0 1 .426 1.31L8.853 6.926l.41 2.393a.768.768 0 0 1-1.114.81L6 9Z"
            id="b"/>
    </defs>
    <g fill="none" fill-rule="evenodd">
        <use fill="url(#a)" xlink:href="#b"/>
        <path d="M0 0h12v12H0z"/>
    </g>
</svg>
```

**Comment by malie666** [comment]
@laleksiunas Hi, I'm not sure if it's because I use svgr and transforme to jsx. It seems the attribute `xlink:href` is transformed to `xlinkHref`. So it affects this logic

https://github.com/laleksiunas/inline-svg-unique-id/blob/17cff0f6b1d7e9daa5e5c372407a77a3f8918911/packages/babel-plugin-react-inline-svg-unique-id/src/plugin.js#L44

![1](https://user-images.githubusercontent.com/26760281/151128136-49f4ff59-b2c5-4bf4-bf60-f34f7ebe6216.png)

![2](https://user-images.githubusercontent.com/26760281/151128159-d511467c-8095-4354-9866-52fce615366e.png)

**Comment by laleksiunas** [comment]
Thanks for your help @Gulululala, I published version 1.3.1 which includes a check for `xlinkHref` as well.

**Comment by laleksiunas** [comment]
Closing because the fix is published. Feel free to reopen if the issue persists.

**Comment by julia-fix** [comment]
Latest version on npm is 1.2.3. How can I add version 1.3.1 to my project?
